// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  VITE_SUPABASE_URL: string;
  VITE_SUPABASE_KEY: string;
  VITE_FRONTEND_URL: string;
  VITE_TWITTER_CLIENT_ID: string;
  TWITTER_BEARER_TOKEN: string;
  TWITTER_CLIENT_SECRET: string;
  XAI_API_KEY: string;
  FAKE_API: string;
}
