// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  XAI_API_KEY: string;
  OPENAI_API_KEY: string;
  TWITTER_USERNAME: string;
  TWITTER_PASSWORD: string;
  TWITTER_EMAIL: string;
  SUPABASE_URL: string;
  SUPABASE_KEY: string;
  TWITTER_API_KEY: string;
  TWITTER_API_SECRET: string;
  TWITTER_ACCESS_TOKEN: string;
  TWITTER_ACCESS_SECRET: string;
  TWITTER_BEARER_TOKEN: string;
  FAKE_API: boolean;
}
