// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  GROK_API_KEY: string;
  GROK_BASE_URL: string;
  SUPABASE_URL: string;
  SUPABASE_KEY: string;
  TWITTER_CLIENT_ID: string;
  FAKE_API: string;
  FRONTEND_URL: string;
}
