#:schema node_modules/wrangler/config-schema.json
name = "bob-worker"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
SUPABASE_URL = "https://ypswcnhnviqsfrxzvmqx.supabase.co"
SUPABASE_KEY = "your-supabase-key"
TWITTER_CLIENT_ID = "SkpzYU1IZE5XY1ZhYzZST194MFE6MTpjaQ"
FRONTEND_URL = "http://localhost:5173"
FAKE_API = false
GROK_API_KEY = "your-grok-key"
GROK_BASE_URL = "https://your-grok-endpoint/v1"
TWITTER_API_KEY = "your-twitter-api-key"
TWITTER_API_SECRET = "your-twitter-api-secret"
TWITTER_ACCESS_TOKEN_SECRET = "your-twitter-access-token-secret"
TWITTER_ACCESS_TOKEN = "your-twitter-access-token"
TWITTER_BEARER_TOKEN = "your-twitter-bearer-token"
