#:schema node_modules/wrangler/config-schema.json
name = "bob-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "BOB_KV", id = "1e92199854d34f5581c304b3c83f9e6d", preview_id = "0b1de42bdbe84d7eb1ec36c7d5c555e7" }
]

[vars]
ENVIRONMENT = "production"
VITE_SUPABASE_URL = "https://dpvqstbzuseeikozgzje.supabase.co"
VITE_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdnFzdGJ6dXNlZWlrb3pnemplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MjYxMzIsImV4cCI6MjA1MDAwMjEzMn0.6p_pRmyqn_kBSZw-0Se78tQ3Pp2U9kE_7w0SWb6wUrQ"
VITE_FRONTEND_URL = "http://localhost:5173"
VITE_TWITTER_CLIENT_ID = "aUt0aTZDMHZvX0pGMU83V2dBQjE6MTpjaQ"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAD3VxAEAAAAAurMUrYco4TmY1nntnu9iK7PKNos%3DuY9JIU9KluVDXGCA7uRAYEFf4lCQfkV3qMhZyBbAOHogEkIL9c"
TWITTER_CLIENT_SECRET = "jQYLKjgSVuFDrEadaDVH5p6-FxbOFMtzVwpXNUDTB6fMxsscs1"
XAI_API_KEY = "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"
VITE_SERVER_URL = "https://bob-worker.affaan.workers.dev"

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.ts"]
