#:schema node_modules/wrangler/config-schema.json
name = "bob-worker"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
SUPABASE_URL = "https://ypswcnhnviqsfrxzvmqx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwc3djbmhudmlxc2ZyeHp2bXF4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyODY1MzAyMiwiZXhwIjoyMDQ0MjI5MDIyfQ._6QTdz5b_K5yo9MQvJqOraoZ3uR1J_7Z1jNg8xWRVwQ"
TWITTER_CLIENT_ID = "SkpzYU1IZE5XY1ZhYzZST194MFE6MTpjaQ"
FRONTEND_URL = "http://localhost:5173"
FAKE_API = true
GROK_API_KEY = "xai-uAJbLrZ6GkXyLfxbuSHSQFrWzbUJkRGRkPhMckVRZVOH4LYVy8PKRxhiODyONf5Hb7c2WSZbt88U94oK"
GROK_BASE_URL = "https://api.x.ai/v1"
TWITTER_API_KEY = "Mk0xAGryk5uOTUjqDfvRBcHIF"
TWITTER_API_SECRET = "N7orAKLTOhqiAsDygoUFmHC9ANxfpG43Zi3RL8Ysik2aG8c79g"
TWITTER_ACCESS_TOKEN_SECRET = "g2aXVMDBmvEq8NRZjpvahY7a2FiWgvgGJUFN8GK6mcCDG"
TWITTER_ACCESS_TOKEN = "1830340867737178112-ehOKtvfzpb7s1gXkvsWQb3mf1dgJRL"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAPppwQEAAAAAYSi1vFW0YAokGo1ol%2Bm55d5PacI%3DvVMqtbYnYO1ncLTjWxNtK07CUqgbSGfqnBy6DbD3Qq3vtWOQbG"
