#:schema node_modules/wrangler/config-schema.json
name = "bob-worker"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
SUPABASE_URL = "https://ypswcnhnviqsfrxzvmqx.supabase.co"
TWITTER_CLIENT_ID = "SkpzYU1IZE5XY1ZhYzZST194MFE6MTpjaQ"
FRONTEND_URL = "https://basedorbiased.vercel.app"
FAKE_API = false
GROK_BASE_URL = "https://api.x.ai/v1"